### ISSUE TITLE
Adaptive documents list

### ISSUE THREAD

**Issue by ninabondar** [ninabondar/epigma#10]
There is no adaptive docs list version for tablet and mobile.

**Comment by Shumyk** [comment]
I will take it with pleasure.

**Comment by martyns0n** [comment]
@ninabondar I'm sorry, but maybe it's already been done.

**Comment by Shumyk** [comment]
#16 Add CSS rules to make document list adaptive.

@martyns0n ups, I also implemented it meanwhile. :)
