### ISSUE TITLE
No need in burger menu

### ISSUE THREAD

**Issue by ninabondar** [ninabondar/epigma#9]
The left corner menu now has weird interface. There is only on action possible and no need to have a drop-down list of actions. Please refactor to a more user-friendly intrface.

**Comment by Shumyk** [comment]
Gonna take this.

**Comment by roh8raut** [comment]
I will take this

**Comment by Shumyk** [comment]
#11 
Pull request

**Comment by ninabondar** [comment]
@roh8raut  thank you for your interest! 
These days I am refactoring the project. In the future, I am going to shift it to Typescript's side from Flow. If you are interested in participating, please feel free to track the issues I'll open in the nearest future.

**Comment by roh8raut** [comment]
Yes ,sure i'll look forward towards it
